name: calendar_app
description: A simple calendar app with task management and statistics.
version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5
  flutter_local_notifications: ^14.0.0
  date_time_picker: ^2.0.0
  charts_flutter: ^0.12.0
  webview_flutter: ^4.2.2 # Added dependency for WebView functionality

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
